on:
  push:
    tags:
      - "v*"
name: Package Release
env:
  # the name of the repo
  HOME_REPO: usnistgov/OSCAL
  # dependency versions
  SAXON_VERSION: 9.9.1-3
  HUGO_VERSION: 0.69.2
  # build-specific environment
  CONTENT_CONFIG_PATH: src/config
  SCHEMATRON_HOME: git-content/schematron
  OSCAL_HOME: git-content/oscal
  OSCAL_CICD_PATH: git-content/oscal/build/ci-cd
  OSCAL_WORKING_PATH: git-content/oscal
  OSCAL_WEBSITE_PATH: git-content/oscal/docs
  OSCAL_SCRATCH_PATH: oscal-scratch
jobs:
  tagged-release:
    name: Package GitHub Release
    runs-on: ubuntu-18.04
    steps:
      # use this for main repo master builds
      - uses: actions/checkout@v3
        if: github.repository == env.HOME_REPO
        with:
          path: ${{ env.OSCAL_HOME }}
          submodules: recursive
          token: ${{ secrets.COMMIT_TOKEN }}
      - name: Set env
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/*/}"
          RELEASE_VERSION="${RELEASE_TAG#"v"}"
          RELEASE_NAME="oscal-${RELEASE_VERSION}"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
      - name: Package Release
        run: |
          bash "${OSCAL_CICD_PATH}/package-release.sh" "${OSCAL_WORKING_PATH}"
          tar -jcvf "${RELEASE_NAME}.tar.bz2" -C "${OSCAL_WORKING_PATH}/archive" .
          (cd "${OSCAL_WORKING_PATH}/archive" && zip -r "../${RELEASE_NAME}.zip" .)
      - uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            "${{ env.OSCAL_WORKING_PATH }}/${{ env.RELEASE_NAME }}.tar.bz2"
            "${{ env.OSCAL_WORKING_PATH }}/${{ env.RELEASE_NAME }}.zip"
          retention-days: 5
      - uses: ncipollo/release-action@v1
        with:
          name: OSCAL ${{ env.RELEASE_VERSION }} Release
          draft: true
          prerelease: true
          token: ${{ secrets.COMMIT_TOKEN }}
          artifacts: "${{ env.RELEASE_NAME }}.tar.bz2,${{ env.RELEASE_NAME }}.zip"
